DATASET_DIR = './dataset/resize'
LABELS_CSV = './dataset/labels.csv'

RESIZE_HEIGHT = 180
RESIZE_WIDTH = 320

BATCH_SIZE = 32
NUM_WORKERS = 4
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-5
CLIP_GRAD_NORM = 5.0
EPOCHS = 200
EARLY_STOPPING_PATIENCE = 10
# LR scheduler settings
REDUCE_LR_ON_PLATEAU = True
REDUCE_LR_FACTOR = 0.5
REDUCE_LR_PATIENCE = 3
MIN_LR = 1e-6

# Model regularization
DROPOUT_PROB = 0.4
USE_BATCHNORM = True
